### ISSUE TITLE
porcelain.pull raises exception when there's a new local commit

### ISSUE THREAD

**Issue by henning** [jelmer/dulwich#1307] opened 2024-05-04 18:36 UTC
I am working on a web application that stores some data in a local git repository that is also synced to a remote, and this remote should also receive commits from other manually made and modified clones.

That means, when I use dulwich to commit something, before I can push the changes, I also must pull possible changes from the remote first.

But when trying to do a porcelain.pull() after a commit, I get a DivergedBranches exception.

As the docs of the porcelain state that porcelain should be expected to work just as the command line client and other behaviour would be considered a bug, here I am reporting it... 

Version i tested the behaviour with: 
0.22.1 from github, 0.21.2-1+b1 from debian bookwork

Steps to reproduce:

* create a repository
* clone the repository with a command line client(easier - i realized porcelain.clone() seems not to properly setup an upstream branch to pull/push to and i didn't find out how to make that just with dulwich/porcelain - maybe that is another bug in terms of "doesn't behave like the standard git CLI)
* add a file and commit the change(should be fine with porcelain or git cli)
* use dulwich function in a script/interactive python interpreter:

```
repo = Repo('/path/to/repo_clone')
porcelain.push(repo) 
```

Expected result:

Some message/confirmation about the pull being successful / nothing being pulled as no changes upstream.

Observed result:

the command errors out with a DivergedBranches exception:

```
Traceback (most recent call last):
  File "/work/emsv/tests/manual/dulwich_pull_testing.py", line 56, in <module>
    porcelain.pull(clone_repo)
  File "/usr/lib/python3/dist-packages/dulwich/porcelain.py", line 1303, in pull
    check_diverged(r, r.refs.follow(rh)[1], fetch_result.refs[lh])
  File "/usr/lib/python3/dist-packages/dulwich/porcelain.py", line 357, in check_diverged
    raise DivergedBranches(current_sha, new_sha)
dulwich.porcelain.DivergedBranches: (b'e261defa2c51c121fdf8f9209d0b3f6dd815015c', b'c8dae00d119cf8f567c2534674bb11c61c69cfc8')

```

NOTE:

This bug is NOT(yet) about a workflow when the central repository really has been changed from another side.
If I just wanted to push the changes to the remote that has no changes, I can just do a push without a pull, that will work.

BUT when the central repository really also has changes from another client, push does also not work and raise a DivergedBranches error. But it seems like I have no possibility to resolve that.

I also know that dulwich/porcleain doesn't support merges, and that things will get much more complicated when the pull can no be simply fast-forwared - but for now i just want to get the simple, nonconflicting cases going...

**Comment by jelmer** [comment] 2024-05-04 22:31
I'm not sure that I follow this bug. Can you provide a simple python script that reproduces it?

**Comment by henning** [comment] 2024-05-05 11:23
thanks for the quick reply!
But im not sure if i understand the question / what exactly the script should contain.

The steps to reproduce are above in the description.

Can you let me know what exactly of these steps is not clear enough?

what i can do for now is trying to rephrase it:

given a repository cloned from a remote, after changing a file and committing it, when i do:

porcelain.pull(repo_location)

in order to get the current state of the remote before pushing the local changes, i get a DivergedBranches exception.

**Comment by jelmer** [comment] 2024-05-05 12:17
so for my understanding, the remote branch has *no* extra commits that are not present locally? i.e. the local branch has the same commits as the remote branch, plus one more?

**Comment by henning** [comment] 2024-05-05 13:02
correct.

strictly speaking a pull would not be necessary in that case.

but in my application i want to do it to ensure that a subsequent push will succeed.

**Comment by henning** [comment] 2024-05-05 17:19
One addition i forgot to add: 

What I meant with the last sentence of the previous comment is: 

*if* the remote also has an additional commit, a push will not work. 
Then i *have* to do a pull before the push. But it also fails. 

With the git CLI, this is a standard workflow that just works, as long as the additional commit on the remote and the additional local commit  dont conflict.

**Comment by jelmer** [comment] 2024-05-05 22:02
> if the remote also has an additional commit, a push will not work.
> Then i have to do a pull before the push. But it also fails.

but that pull would not be a fast-forward pull, it would require merging - which is why you're getting the DivergedBranches error. With the git cli, if you invoked "git pull --ff-only" here it would also not work.

**Comment by henning** [comment] 2024-05-06 15:54
Yes you are right! I mixed that up... 

Actually we are now on the problem i actually wanted to solve for my own use case.

While in first place i wanted to report the bug as the documentation said it's a bug when porcelain behaves different than git cli so I understood you wanted to know when people find such cases.
One could argue that's the case because git cli doesn't error out when the local is one commit ahead, and none behind the remote and i do a git pull that would actually no be necessary. But I'm not sure if that is a problematic difference.
So i can just close the issue from my side.

But my actual use case, do i see it right that it cannot be solved with dulwich, as i read merges are generally not supported? Or are there lower level command that could do it?

**Comment by jelmer** [comment] 2024-05-06 18:09
> But my actual use case, do i see it right that it cannot be solved with dulwich, as i read merges are generally not supported? Or are there lower level command that could do it?

Unfortunately it's indeed not possible with Dulwich today due to missing merge support.

**Comment by jelmer** [comment] 2024-05-07 11:48
Closing this, since we already have a bug open about merge support

**Closed** 2024-05-07 11:48 UTC
Labels: moreinfo
