### ISSUE TITLE
dulwich.index.get_unstaged_changes fails if any files in the index do not exist in the working copy

### ISSUE THREAD

**Issue by jsbain** [jelmer/dulwich#412] opened 2016-02-13 16:16 UTC
i.e doing an rm without removing from the index.
In developing a fix, would the preference be that get_unstaged_changes should include such a file as a change?  This prbably requires checks everywhere else that uses the output of this function, where it is important when missing files are handled differently than changed ones.

Or, should should this function only return changed files, and maybe we add a new get_unstaged_removals?  Or should we return a tuple `changed_files, removed_files`?

**Comment by jelmer** [comment] 2016-02-15 12:07
On Sat, Feb 13, 2016 at 08:16:46AM -0800, jsbain wrote:
> i.e doing an rm without removing from the index.
> In developing a fix, would the preference be that get_unstaged_changes should include such a file as a change?  This prbably requires checks everywhere else that uses the output of this function, where it is important when missing files are handled differently than changed ones.
> 
> Or, should should this function only return changed files, and maybe we add a new get_unstaged_removals?  Or should we return a tuple `changed_files, removed_files`?
Yeah, I think it would be reasonable to include removed files there.

> [as an aside.. is it possible to run the test suite from an interactive py session, or only through make check?  ]
You should be able to run it interactively. make check is just running "python -m unittest dulwich.tests.test_suite".

Jelmer

**Comment by jelmer** [comment] 2017-01-15 14:55
This is a dupe of #483, which has since been fixed.

**Closed by jelmer** 2017-01-15 14:55 UTC
Labels: bug
