### ISSUE TITLE
Git hooks are not being executed

### ISSUE THREAD

**Issue by jreinert** [jelmer/dulwich#386] opened 2015-10-26 17:49 UTC
Hi, I already opened this issue in at Radicale which uses dulwich for git integration. My post-commit hook isn't executed for some reason. It's in `.git/hooks` and it's called `post-commit`, it's executable and it's a bash script. It works if i do a manual commit. Any ideas?

**Comment by jelmer** [comment] 2015-10-26 23:03
On Mon, Oct 26, 2015 at 10:49:19AM -0700, Joakim Reinert wrote:
> Hi, I already opened this issue in at Radicale which uses dulwich for git integration. My post-commit hook isn't executed for some reason. It's in `.git/hooks` and it's called `post-commit`, it's executable and it's a bash script. It works if i do a manual commit. Any ideas?

Can you reproduce this when you do a commit using 'dulwich commit' ?

What version of dulwich are you using?

Cheers,

Jelmer

**Comment by jelmer** [comment] 2015-10-31 21:40
ping?

**Comment by jelmer** [comment] 2016-07-03 14:10
Probably a dupe of #212.

**Closed by jelmer** 2016-07-03 14:10 UTC
