### ISSUE TITLE
unexpected Python 3.6 behavior of ConfigDict.get()

### ISSUE THREAD

**Issue by carlwgeorge** [jelmer/dulwich#508] opened 2017-03-09 02:59 UTC
I would like to use this library to obtain the origin remote url in Python 3.6, but ran into an error that doesn't occur under Python 2.7.

```python
from __future__ import print_function
from dulwich import porcelain
repo = porcelain.open_repo('.')
config = repo.get_config()
url = config.get(('remote', 'origin'), 'url')
print(url)
```
```
(env2.7) $ python test.py
https://github.com/jelmer/dulwich.git
```
```
(env3.6) $ python test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    url = config.get(('remote', 'origin'), 'url')
  File "/home/carl/development/dulwich/dulwich/config.py", line 155, in get
    return self._values[(section[0],)][name]
KeyError: ('remote',)
```
After looking over the code, I realized I could get it to work by using bytestrings with the `.get` method.
```diff
-url = config.get(('remote', 'origin'), 'url')
+url = config.get((b'remote', b'origin'), b'url')
```
```
(env3.6) $ python test.py 
b'https://github.com/jelmer/dulwich.git'
```

Is this the expected/desired behavior?  According the the [documentation](https://dulwich.io/docs/tutorial/encoding.html), "Higher level functions, such as the porcelain in dulwich.porcelain, will automatically convert unicode strings to UTF-8 bytestrings".  That doesn't seem to be happening here.  I'm happy to send a pull request for this once I get some clarification.

**Comment by jelmer** [comment] 2017-03-09 16:32
The only real high level part is the porcelain. It has some functions (but not complete coverage) for dealing with remotes.

The config class only deals with bytestrings, it's just that python 2 defaults to bytestrings. I'm not opposed to making the config class understand Unicode strings, bun afaik git just treats it as bytes too - it doesn't mandate that the config file is valid utf8.

**Comment by jelmer** [comment] 2017-03-31 19:16
Closing this for now, as it's working as intended. Feel free to reopen if you have suggestions.

**Closed by jelmer** 2017-03-31 19:16 UTC
