### ISSUE TITLE
dulwich.repo.Repo.get_refs fails when a tag contains non-ASCII characters

### ISSUE THREAD

**Issue by hoelzro** [jelmer/dulwich#308] opened 2015-05-28 15:41 UTC
If I have a tag in a Git repo that contains non-ASCII characters, (for example, schön), dulwich.repo.Repo.get_refs fails with a UnicodeEncodeError:

```python
# encoding: utf-8

import os
import os.path
import tempfile

from dulwich.repo import Repo

tempdir = tempfile.mkdtemp()

os.spawnlp(os.P_WAIT, 'git', 'git', 'init', tempdir)
os.environ['GIT_DIR']=os.path.join(tempdir, '.git')
os.environ['GIT_WORK_TREE']=os.path.join(tempdir)

os.spawnlp(os.P_WAIT, 'git', 'git', 'commit', '--allow-empty', '-m', 'Test commit')
os.spawnlp(os.P_WAIT, 'git', 'git', 'tag', 'schön')

r = Repo(tempdir)
print r.get_refs()
```

    Initialized empty Git repository in /tmp/tmpyttgzY/.git/
    [master (root-commit) 2d832d8] Test commit
    Traceback (most recent call last):
      File "test.py", line 19, in <module>
        print r.get_refs()
      File "/tmp/dulwich/dulwich/repo.py", line 306, in get_refs
        return self.refs.as_dict()
      File "/tmp/dulwich/dulwich/refs.py", line 149, in as_dict
        keys = self.keys(base)
      File "/tmp/dulwich/dulwich/refs.py", line 128, in keys
        return self.allkeys()
      File "/tmp/dulwich/dulwich/refs.py", line 419, in allkeys
        refname = ("%s/%s" % (dir, filename)).strip("/").encode('ascii')
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 13: ordinal not in range(128)

**Comment by jelmer** [comment] 2015-05-30 11:02
What platform/python version are you on?

**Comment by hoelzro** [comment] 2015-05-30 15:18
Python 2.7.9 via virtualenv on Arch Linux, using dulwich installed via `pip install git+git://github.com/jelmer/dulwich`.

**Comment by jelmer** [comment] 2015-05-30 19:27
On Sat, May 30, 2015 at 08:18:27AM -0700, Rob Hoelz wrote:
> Python 2.7.9 via virtualenv on Arch Linux, using dulwich installed via `pip install git+git://github.com/jelmer/dulwich`.
Thanks.

Looks like this is a regression in HEAD.

**Comment by jelmer** [comment] 2015-05-31 18:30
Fixed in master.

**Closed by jelmer** 2015-05-31 18:30 UTC
Labels: bug

**Comment by curaloucura** [comment] 2015-07-27 12:28
Seems like subkeys function was missed and it's blowing up for us:

https://github.com/jelmer/dulwich/commit/0959a6f85c5dadb4229a6ede9a94f66695559a0f#diff-68db177312d4b6a6396be97b3def4771R401

**Comment by jelmer** [comment] 2015-07-27 12:29
On Mon, Jul 27, 2015 at 05:28:12AM -0700, Anderson Santos wrote:
> Seems like subkeys function was missed and it's blowing up for us:
> 
> https://github.com/jelmer/dulwich/commit/0959a6f85c5dadb4229a6ede9a94f66695559a0f#diff-68db177312d4b6a6396be97b3def4771R401

Can you paste a backtrace?

**Comment by curaloucura** [comment] 2015-07-27 12:42
Sure, and I just changed that line according to the other function and worked fine:

https://gist.github.com/curaloucura/17bb6f7c38889d35f87b

**Comment by jelmer** [comment] 2015-07-29 01:49
Please try again with current HEAD.

**Comment by curaloucura** [comment] 2015-07-30 14:29
Working smoothly now, thank you
