### ISSUE TITLE
No feedback when exceeding github's file limit (push)

### ISSUE THREAD

**Issue by speter18** [jelmer/dulwich#924] opened 2022-01-20 09:51 UTC
When using `porcelain.push` to push to github and there are files included that exceed githubs file limit (100MB), no exception is thrown. The call silently runs through, while in the terminal an error occurs, when calling `git push`.

**Comment by jelmer** [comment] 2022-01-23 22:43
Do you have a script that reproduces this issue? the porcelain should just forward any errors from the remote server to stderr.

**Comment by jelmer** [comment] 2022-03-06 01:23
ping? This is not something that should be enforced on the Dulwich side, but errors should be propagated. Does that not happen?

**Comment by jelmer** [comment] 2022-06-12 23:09
closing this since there has been no follow-up and I can't reproduce it

**Closed by jelmer** 2022-06-12 23:09 UTC
Labels: bug, moreinfo
