### ISSUE TITLE
Extra Slash Required after Host Name

### ISSUE THREAD

**Issue by mstonespeedy** [jelmer/dulwich#463] opened 2016-11-09 00:59 UTC
I'm using dulwich 0.12.2 with Pythonista iOS and StaSh. I am successfully connecting to our company Git server through ssh. However, about 6 seconds after I try a git clone ssh://..., I get the error:

`stash: <class 'dulwich.errors.HangupException'>: The remote server unexpectedly closed the connection.`

The server logs show a successful session open, but they don't show a session close message until 3 minutes later. Since I can ssh into the server just fine, it seems to be an issue with dulwich.

When I add another slash after the host name, it works:

`git clone ssh://user@git.myCompany.com//git/MyRepository.git`

It shouldn't require the extra slash.

**Comment by jelmer** [comment] 2016-11-10 10:43
On Tue, Nov 08, 2016 at 04:59:26PM -0800, mstonespeedy wrote:
> I'm using dulwich 0.12.2 with Pythonista iOS and StaSh. I am successfully connecting to our company Git server through ssh. However, about 6 seconds after I try a git clone ssh://..., I get the error:
> 
> `stash: <class 'dulwich.errors.HangupException'>: The remote server unexpectedly closed the connection.`
> 
> The server logs show a successful session open, but they don't show a session close message until 3 minutes later. Since I can ssh into the server just fine, it seems to be an issue with dulwich.
> 
> When I add another slash after the host name, it works:
> 
> `git clone ssh://user@git.myCompany.com//git/MyRepository.git`
> 
> It shouldn't require the extra slash.
Is the server Dulwich in your case? How is it started?

Jelmer

**Comment by mstonespeedy** [comment] 2016-11-10 16:25
This is our server information:

```
Ubuntu 12.04.5 LTS (GNU/Linux 3.13.0-100-generic x86_64)
git version 1.7.9.5
```

**Comment by jelmer** [comment] 2016-11-10 17:37
On Thu, Nov 10, 2016 at 08:25:34AM -0800, mstonespeedy wrote:
> This is our server information:
> 
> ```
> Ubuntu 12.04.5 LTS (GNU/Linux 3.13.0-100-generic x86_64)
> git version 1.7.9.5
> ```

I'm not sure I follow - both your server and your client seem to be C git. How
are you using Dulwich?

**Comment by mstonespeedy** [comment] 2016-11-10 19:24
As I mentioned in my first comment: I'm using dulwich 0.12.2 with Pythonista iOS (Python interpreter) and StaSh (shell <https://github.com/ywangd/stash>). The StaSh git ssh connection uses dulwich.

Please let me know if there is anything I can do to help you debug this issue.

**Comment by jelmer** [comment] 2016-11-10 20:47
On Thu, Nov 10, 2016 at 11:24:31AM -0800, mstonespeedy wrote:
> As I mentioned in my first comment: I'm using dulwich 0.12.2 with Pythonista iOS (Python interpreter) and StaSh (shell <https://github.com/ywangd/stash>). The StaSh git ssh connection uses dulwich.
> 
> Please let me know if there is anything I can do to help you debug this issue.

Can you run the following commands (on the command-line, not from stash):

dulwich clone ssh://user@git.myCompany.com/git/MyRepository.git repo1
git clone ssh://user@git.myCompany.com/git/MyRepository.git repo2
dulwich clone ssh://user@git.myCompany.com//git/MyRepository.git repo3
git clone ssh://user@git.myCompany.com//git/MyRepository.git repo4

**Comment by jsbain** [comment] 2016-11-11 05:10
Pythonista on ios is more of a IDLE style interactive interpreter for ios.   stash adds a bash-like shell on top of this.  So there is no commandline per se, other than stash

For what its worth, we did some troubleshooting in [this thread](https://forum.omz-software.com/topic/3530/git-clone-ssh-failing/7?page=1), the upshot of which is:
    1) He does not have this issue with dulwich+ github, or if using another app with his company server... 
    2) We tried a very simple get_transport_and_path, then `proto, can_read = client._connect(b'upload-pack', host_path)`.  can_read returned false until, both slashs were included (i.e, host_path needed a leading slash)

Also FWIW, we are using a slightly modified dulwich 12.2.2.  i will double check whether get_transport_and_path returns the same host_path in the latest version

**Comment by jelmer** [comment] 2016-11-11 12:45
On Thu, Nov 10, 2016 at 09:10:58PM -0800, jsbain wrote:
> Pythonista on ios is more of a IDLE style interactive interpreter for ios.   stash adds a bash-like shell on top of this.  So there is no commandline per se, other than stash
> 
> For what its worth, we did some troubleshooting in [this thread](https://forum.omz-software.com/topic/3530/git-clone-ssh-failing/7?page=1), the upshot of which is:
>     1) He does not have this issue with dulwich+ github, or if using another app with his company server... 
So you can't reproduce this with C Git?

>     2) We tried a very simple get_transport_and_path, then `proto, can_read = client._connect(b'upload-pack', host_path)`.  can_read returned false until, both slashs were included (i.e, host_path needed a leading slash)
> 
> Also FWIW, we are using a slightly modified dulwich 12.2.2.  i will double check whether get_transport_and_path returns the same host_path in the latest version 

Are you using the default SubprocessSSHVendor, or the Paramiko one? Can you reproduce it with both?

Jelmer

**Comment by jsbain** [comment] 2016-11-11 16:14
Correct, there is no C git inside pythonista.
This uses paramiko, as there is no subprocess (ios apps cannot use subprocesses).

**Comment by jelmer** [comment] 2016-11-11 16:34
On Fri, Nov 11, 2016 at 08:14:12AM -0800, jsbain wrote:
> Correct, there is no C git inside pythonista.
> This uses paramiko, as there is no subprocess (ios apps cannot use subprocesses).
Can you please try this on a desktop computer with the subprocess SSH? Ideally with just "dulwich clone ssh://host:port/bla"

I don't really trust the Paramiko SSH implementation, as it doesn't have any
tests, and that's also why it lives in contrib.

Jelmer

**Comment by jelmer** [comment] 2016-11-28 23:07
Can you please try this on a desktop computer with the subprocess SSH but the same URL? Ideally with just running "dulwich clone ssh://host:port/bla" on the command-line.

**Comment by mstonespeedy** [comment] 2016-11-28 23:48
Sorry, I don't have dulwich installed outside of StaSh in Pythonista.

I believe @jsbain was going to check into get_transport_and_path returning the same host_path in the latest version of dulwich.

**Comment by rst12** [comment] 2017-02-27 19:38
in dulwich 0.16.4 pure python install I might be hitting this issue in ssh-communication to, when I do
>>> from dulwich import porcelain
I got an error with
>>> porcelain.clone('ssh://git@SERVERIP/home/git/remote/.git','remote')
but OK with // after SERVERIP
>>> porcelain.clone('ssh://git@SERVERIP//home/git/remote/.git','remote')

I changed the following part of client.py 
def get_transport_and_path_from_url(url, config=None, **kwargs):
from
        """
        if path.startswith('/'):
            path = parsed.path[1:]
        """
to
        if path.startswith('/'):
            path = parsed.path[0:]

It works now with ssh://git@SERVERIP/home/git/remote/.git' like I would expect it from git.

**Comment by jelmer** [comment] 2017-02-27 23:13
Fixed in master; we only need to drop the slash for paths starting with /~/.

**Closed by jelmer** 2017-02-27 23:13 UTC
Labels: bug
